IF (ARGTABLE3_ROOT)
    # force re-find programs
    set(ARGTABLE3_LIBRARY NOTFOUND CACHE FILE "" FORCE)
    set(ARGTABLE3_INCLUDE_DIR NOTFOUND CACHE PATH "" FORCE)
ENDIF (ARGTABLE3_ROOT)

FIND_LIBRARY(ARGTABLE3_LIBRARY argtable3 HINTS ${ARGTABLE3_ROOT} PATH_SUFFIXES "lib")
FIND_PATH(ARGTABLE3_INCLUDE_DIR argtable3.h HINTS ${ARGTABLE3_ROOT} PATH_SUFFIXES "include")

IF (ARGTABLE3_INCLUDE_DIR AND ARGTABLE2_LIBRARY)
   SET(ARGTABLE3_FOUND TRUE)
ENDIF (ARGTABLE3_INCLUDE_DIR AND ARGTABLE2_LIBRARY)


IF (ARGTABLE3_FOUND)
   IF (NOT ARGTABLE3_FIND_QUIETLY)
      MESSAGE(STATUS "Found Argtable2: ${ARGTABLE3_LIBRARY}")
   ENDIF (NOT ARGTABLE3_FIND_QUIETLY)
ELSE (ARGTABLE3_FOUND)
   IF (ARGTABLE3_FIND_REQUIRED)
      MESSAGE(WARNING "Could not find Argtable2")
   ENDIF (ARGTABLE3_FIND_REQUIRED)
ENDIF (ARGTABLE3_FOUND)
